KAA-1133: Your first Kaa application - reviewed.
kaaproject/kaa pull request #1030
Opened 2016-08-31 09:17 UTC by hunch7

2016-09-08 12:47 UTC, rasendubi commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +This section discusses the basics of creating Kaa-based applications using the [Kaa Sandbox]({{root_url}}Glossary/kaa-sandbox).
Link is broken

2016-09-09 09:03 UTC, hunch7 commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +This section discusses the basics of creating Kaa-based applications using the [Kaa Sandbox]({{root_url}}Glossary/kaa-sandbox).
Fixed.

2016-09-14 22:41 UTC, vadimol commented
@kaa-leeroy re-test this please.

2016-09-14 22:51 UTC, vadimol commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +2. Create a direcory named **kaa** and unpack the C SDK archive it it.
mistype: it it

2016-09-14 22:51 UTC, vadimol commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +		find_package(OpenSSL REQUIRED)
remove this line please, we do not need OpenSSL any more

2016-09-14 22:52 UTC, vadimol commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +		target_link_libraries(kaa-app kaac crypto)
please, change to
target_link_libraries(kaa-app kaac)

2016-09-14 22:58 UTC, vadimol requested changes
Few minor comment were added. Please, take a look. 
Overall, looks good to me.

Regarding source code for C/C++, we will retest and update this guide anyway, so do not pay too much attention.

2016-09-15 07:18 UTC, hunch7 commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +2. Create a direcory named **kaa** and unpack the C SDK archive it it.
Fixed.

2016-09-15 07:18 UTC, hunch7 commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +		find_package(OpenSSL REQUIRED)
Done.

2016-09-15 07:18 UTC, hunch7 commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +		target_link_libraries(kaa-app kaac crypto)
Done.

2016-09-15 07:21 UTC, rasendubi commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +		sudo apt-get install libssl-dev
We also don't need this line.

2016-09-15 07:21 UTC, rasendubi commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +1. Install CMake and OpenSSL.
OpenSSL is not needed.

2016-09-15 07:26 UTC, hunch7 commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +1. Install CMake and OpenSSL.
Fixed.

2016-09-15 07:26 UTC, hunch7 commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +		sudo apt-get install libssl-dev
Fixed.

2016-09-15 07:55 UTC, vadimol approved these changes

2016-09-18 11:53 UTC, vadimol commented
@hunch7 , please resolve merge conflicts and assign the Jira issue to me.

2016-09-19 13:04 UTC, hunch7 commented
New input data added by developer, need to review again. Will make a new branch and a new PR. Closing this PR.

2016-09-19 13:04 UTC, closed without merging

2016-09-22 10:00 UTC, hunch7 commented
New PR: https://github.com/kaaproject/kaa/pull/1093