KAA-1407 Simplify git flow
kaaproject/kaa pull request #1055
Opened 2016-09-09 12:58 UTC by rasendubi

/cc @akokhanovskyi @Slash32 @ikulikov @vadimol @forGGe

2016-09-09 13:33 UTC, Slash32 commented
LGTM

2016-09-20 10:23 UTC, GamovCoder commented on doc/Customization-guide/How-to-contribute/Git-flow/index.md
> +If you want to backport a bug fix, open your pull request against appropriate release branch.
`s/against appropriate/against the appropriate/g`

2016-09-20 10:25 UTC, GamovCoder commented on doc/Customization-guide/How-to-contribute/Git-flow/index.md
`s/that/it/`

2016-09-20 10:30 UTC, ohamov requested changes

2016-09-20 19:05 UTC, rasendubi commented on doc/Customization-guide/How-to-contribute/Git-flow/index.md
Don't agree. `that` refers to the process of fixing.

2016-09-20 19:06 UTC, rasendubi commented on doc/Customization-guide/How-to-contribute/Git-flow/index.md
> +If you want to backport a bug fix, open your pull request against appropriate release branch.
ok

2016-09-21 14:28 UTC, GamovCoder commented on doc/Customization-guide/How-to-contribute/Git-flow/index.md
my fault, agree

2016-09-24 10:25 UTC, rasendubi commented
Merged

2016-09-24 10:25 UTC, closed without merging