Kaa 1431: Configuration parameter for default notification TTL
kaaproject/kaa pull request #1076
Opened 2016-09-15 12:35 UTC by Pyshankov

2016-09-19 15:12 UTC, Oldnickus commented
@kaa-leeroy test this please

2016-09-19 15:50 UTC, Pyshankov commented
@kaa-leeroy re-test this please

2016-09-26 07:00 UTC, ikulikov commented on server/common/dao/src/main/java/org/kaaproject/kaa/server/common/dao/service/NotificationServiceImpl.java
> +    private int ttl = 7 * 24 * 3600;
The TTL parameter value must be in milliseconds.

2016-09-26 07:01 UTC, ikulikov requested changes

2016-09-26 08:01 UTC, merged