KAA-1356 Cross-compilation guide for C++ SDK (Intel Edison) on Linux platform
kaaproject/kaa pull request #1078
Opened 2016-09-15 14:04 UTC by mlysenko

Updated the previous version of the cross-compilation guide.

2016-09-15 16:22 UTC, vadimol commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Edison/index.md
> -2. Install Avro for host and target. Also Avro depends on some Boost components. So they need to be installed too.
Why did you remove this?

2016-09-15 16:22 UTC, vadimol requested changes

2016-09-15 16:23 UTC, vadimol commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Edison/index.md
>      Copy `${SDKTARGETSYSROOT}/usr/local/lib/libboost_*` object files to Edison's `/usr/local/lib` directory (e.g. using SSH, SCP, etc.).
Please, define the SDKTARGETSYSROOT variable somewhere

2016-09-16 06:56 UTC, mlysenko commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Edison/index.md
> -2. Install Avro for host and target. Also Avro depends on some Boost components. So they need to be installed too.
I added a requirement to install Boost and Avro to the first chapter of the cross-compilation guide as a prerequisite:

> ... perform steps 1 and 2 of the [Linux guide] ... to install Boost and Avro components for your host machine.

I think it makes the guide easier to understand.

2016-09-16 07:03 UTC, mlysenko commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Edison/index.md
>      Copy `${SDKTARGETSYSROOT}/usr/local/lib/libboost_*` object files to Edison's `/usr/local/lib` directory (e.g. using SSH, SCP, etc.).
`SDKTARGETSYSROOT` is defined in `environment-setup-core2-32-poky-linux` file which is generated by installer.

2016-09-16 08:36 UTC, vadimol commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Edison/index.md
> -2. Install Avro for host and target. Also Avro depends on some Boost components. So they need to be installed too.
Got it, thanks

2016-09-16 08:36 UTC, vadimol commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Edison/index.md
>      Copy `${SDKTARGETSYSROOT}/usr/local/lib/libboost_*` object files to Edison's `/usr/local/lib` directory (e.g. using SSH, SCP, etc.).
Got it, thanks

2016-09-16 09:43 UTC, vadimol approved these changes

2016-09-16 09:44 UTC, vadimol commented
@kaa-leeroy retest this please

2016-09-18 11:22 UTC, vadimol approved these changes

2016-09-19 08:43 UTC, merged