KAA-1436: Fix serever and client REST fuctionality for getting credentials status
kaaproject/kaa pull request #1081
Opened 2016-09-16 14:06 UTC by Rib47

2016-09-16 14:06 UTC, kaa-leeroy commented
Can one of the admins verify this patch?

2016-09-20 11:06 UTC, ikulikov commented on server/common/admin-rest-client/src/main/java/org/kaaproject/kaa/server/common/admin/AdminClient.java
>          parameters.add("credentialsId", credentialsId);
Unused variable 'parameters' should be removed.

2016-09-20 11:06 UTC, ikulikov requested changes

2016-09-20 11:20 UTC, Rib47 commented on server/common/admin-rest-client/src/main/java/org/kaaproject/kaa/server/common/admin/AdminClient.java
>          parameters.add("credentialsId", credentialsId);
Fixed

2016-09-20 13:13 UTC, merged