KAA-1225: [Objective-C SDK] Incorrect calculation of log delivery time
kaaproject/kaa pull request #1083
Opened 2016-09-18 21:08 UTC by hamsternik

There were several important changes carried out while performing this ticket (except fixing incorrect calculation of log delivery time and aditing test case):
* added public getter for deliveryRunnerDictionary from AbstractLogCollector class
* added receivedResponseTime property to return the total delivery time of log (in milliseconds).
* implemented new category for NSDate class
* made small code refactoring

2016-09-18 21:10 UTC, hamsternik commented
@abohomol @am1kk please review

2016-09-20 09:59 UTC, am1kk commented on client/client-multi/client-objective-c/Kaa/utils/NSDate+Timestamp.m
> +@end
File must ends with new line.

2016-09-20 09:59 UTC, am1kk commented on client/client-multi/client-objective-c/KaaTests/logging/DefaultLogUploadStrategyTest.m
> +@end
File must ends with new line.

2016-09-20 10:04 UTC, am1kk commented on client/client-multi/client-objective-c/KaaTests/logging/delivery/LogDeliveryTest.m
> +@end
File must ends with new line.

2016-09-20 10:04 UTC, am1kk requested changes

2016-09-20 12:28 UTC, hamsternik commented on client/client-multi/client-objective-c/Kaa/utils/NSDate+Timestamp.m
> +@end
Done.

2016-09-20 12:28 UTC, hamsternik commented on client/client-multi/client-objective-c/KaaTests/logging/DefaultLogUploadStrategyTest.m
> +@end
Done.

2016-09-20 12:28 UTC, hamsternik commented on client/client-multi/client-objective-c/KaaTests/logging/delivery/LogDeliveryTest.m
> +@end
Done.

2016-09-20 12:53 UTC, am1kk approved these changes

2016-09-21 16:09 UTC, abohomol commented on client/client-multi/client-objective-c/Kaa/log/AbstractLogCollector.h
> +- (NSMutableDictionary *)getDeliveryRunnerDictionary;
I'm not seeing that method to be used anywhere outside the AbstractLogCollector class.

2016-09-21 16:13 UTC, abohomol commented on client/client-multi/client-objective-c/Kaa/log/AbstractLogCollector.m
> +				            [self.deliveryRunnerDictionary removeObjectForKey:@(bucketInfo.bucketId)];
Incorrect indention

2016-09-21 16:13 UTC, abohomol commented on client/client-multi/client-objective-c/Kaa/log/BucketRunner.m
> +#import <QuartzCore/QuartzCore.h>
Do we still need this import after we incapsulated time calculation inside NSDate category?

2016-09-21 16:13 UTC, abohomol commented on client/client-multi/client-objective-c/KaaTests/logging/LogDeliveryCallbackTests.m
> +// TODO: NK: Separate this testcase for several sub-testcases (focus on status result)
Possibly redundant/outdated comment

2016-09-21 16:13 UTC, abohomol commented on client/client-multi/client-objective-c/Kaa/log/AbstractLogCollector.m
> +#import <QuartzCore/QuartzCore.h>
Do we still need this import after we incapsulated time calculation inside NSDate category?

2016-09-21 16:13 UTC, abohomol commented on client/client-multi/client-objective-c/Kaa/log/AbstractLogCollector.m
> +				            [self.deliveryRunnerDictionary removeObjectForKey:@(bucketInfo.bucketId)];
As far as I see this method is just moved here out of notifyOnSuccessDeliveryRunnersWithBucketInfo: method.
Is there any reason for that?

2016-09-21 16:15 UTC, abohomol commented on client/client-multi/client-objective-c/KaaTests/logging/delivery/LogDeliveryTest.m
> +	    BucketInfo *bucketInfo = [[BucketInfo alloc] initWithBucketId:status.requestId logCount:1];
Incorrect indention in this line and the one below

2016-09-21 16:17 UTC, abohomol commented on client/client-multi/client-objective-c/KaaTests/logging/delivery/LogDeliveryTest.m
> +	    BucketRunner *brunner = [[BucketRunner alloc] init];
Incorrect indention

2016-09-21 16:17 UTC, abohomol commented on client/client-multi/client-objective-c/KaaTests/logging/delivery/LogDeliveryTest.m
> +	    for (NSInteger i = 0; i < kIterCount; i++) {
Incorrect indention

2016-09-21 16:24 UTC, abohomol requested changes
There are several things that aren't obvious for me. I'd ask for some clarifications on those and insist on fixing minor code style issue.

2016-09-21 18:02 UTC, hamsternik commented on client/client-multi/client-objective-c/Kaa/log/AbstractLogCollector.m
> +#import <QuartzCore/QuartzCore.h>
Of course, no. Removed redundant import.

2016-09-21 18:03 UTC, hamsternik commented on client/client-multi/client-objective-c/Kaa/log/AbstractLogCollector.m
> +				            [self.deliveryRunnerDictionary removeObjectForKey:@(bucketInfo.bucketId)];
Fixed.

2016-09-21 18:03 UTC, hamsternik commented on client/client-multi/client-objective-c/Kaa/log/AbstractLogCollector.m
> +				            [self.deliveryRunnerDictionary removeObjectForKey:@(bucketInfo.bucketId)];
Firstly, the goal of the _notifyOnSuccessDeliveryRunnersWithBucketInfo_ method to setup passed bucket info instance to each of runners stored by concrete bucket info ID.
The next reason is unreasonable removing all runners from local storage (self.deliveryRunnerDictionary). 

So, without moving this line out from _notifyOnSuccessDeliveryRunnersWithBucketInfo_ method, I can't store my bucket info's instances for some more time. And as you can see in **LogDeliveryTest** single test case, I store all bucketInfos for next checking of their bucketDeliveryDuration.

2016-09-21 18:03 UTC, hamsternik commented on client/client-multi/client-objective-c/Kaa/log/BucketRunner.m
> +#import <QuartzCore/QuartzCore.h>
This import is redundant too. Removed.

2016-09-21 18:03 UTC, hamsternik commented on client/client-multi/client-objective-c/KaaTests/logging/LogDeliveryCallbackTests.m
> +// TODO: NK: Separate this testcase for several sub-testcases (focus on status result)
Waste comment. Removed.

2016-09-21 18:03 UTC, hamsternik commented on client/client-multi/client-objective-c/Kaa/log/AbstractLogCollector.h
> +- (NSMutableDictionary *)getDeliveryRunnerDictionary;
Yes, this method had been used at debug process and hasn't been removed after bug fixing. Removed

2016-09-21 18:03 UTC, hamsternik commented on client/client-multi/client-objective-c/KaaTests/logging/delivery/LogDeliveryTest.m
> +	    BucketInfo *bucketInfo = [[BucketInfo alloc] initWithBucketId:status.requestId logCount:1];
Fixed.

2016-09-21 18:03 UTC, hamsternik commented on client/client-multi/client-objective-c/KaaTests/logging/delivery/LogDeliveryTest.m
> +	    BucketRunner *brunner = [[BucketRunner alloc] init];
Fixed.

2016-09-21 18:03 UTC, hamsternik commented on client/client-multi/client-objective-c/KaaTests/logging/delivery/LogDeliveryTest.m
> +	    for (NSInteger i = 0; i < kIterCount; i++) {
Fixed.

2016-09-23 12:28 UTC, abohomol commented
LGTM

2016-09-24 11:04 UTC, rasendubi commented
@kaa-leeroy retest this please

2016-10-09 19:36 UTC, merged