KAA-1371: Your first Kaa application (updated with CTL info).
kaaproject/kaa pull request #1093
Opened 2016-09-21 15:16 UTC by hunch7

2016-09-22 08:58 UTC, ikulikov commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +For the Sandbox, use the default **kaa** username and **kaa123** password.
The way how user should log in to the Sandbox is not clear here. User should login to the Sandbox VM using ssh with kaa/kaa credentials.

2016-09-22 08:59 UTC, ikulikov requested changes

2016-09-22 09:22 UTC, hunch7 commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +For the Sandbox, use the default **kaa** username and **kaa123** password.
Fixed.

2016-09-22 10:02 UTC, merged

2016-09-27 09:06 UTC, Polinaa commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +5. Click the **Applications** arrow to unfold the list and click the arrow of the application you created in [Adding an application](#adding-an-application), then click **Schemas** > **Log** and clic
#add-application

2016-09-27 09:09 UTC, Polinaa commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +	>**NOTE:** Version numbers in the screenshot correspond to the version numbers obtained in [Creating schemas](#creating-schemas).
Bad link, should be __#create-schemas__

2016-09-27 09:12 UTC, Polinaa commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +					"by_default": "1"
"by_default": __1__

2016-09-27 09:20 UTC, Polinaa commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +7. Scroll down and use the **Upload from file** function to find the previously created data-schema.json file and click **Upload**.
Unnecessary step as CT was created and used before (_3_ and _6_ steps).

2016-09-27 10:23 UTC, hunch7 commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +					"by_default": "1"
Fixed.

2016-09-27 10:23 UTC, hunch7 commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +5. Click the **Applications** arrow to unfold the list and click the arrow of the application you created in [Adding an application](#adding-an-application), then click **Schemas** > **Log** and clic
Fixed.

2016-09-27 10:23 UTC, hunch7 commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +7. Scroll down and use the **Upload from file** function to find the previously created data-schema.json file and click **Upload**.
Fixed.

2016-09-27 10:24 UTC, hunch7 commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +	>**NOTE:** Version numbers in the screenshot correspond to the version numbers obtained in [Creating schemas](#creating-schemas).
Fixed.

2016-09-27 10:25 UTC, hunch7 commented
Latest fixes upon QA review: https://github.com/kaaproject/kaa/pull/1114
@ikulikov , please merge.