APP-271: Error after configuring Intel Edison board
kaaproject/kaa pull request #1094
Opened 2016-09-21 17:03 UTC by Dubland

/cc @vadimol @RostakaGmfun

2016-09-22 22:37 UTC, vadimol commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Edison/index.md
> +   ```
_export LD_LIBRARY_PATH=/usr/local/lib_
will be enough to compile the application. It is not necessary to change user's profile.

2016-09-23 07:01 UTC, rasendubi commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Edison/index.md
> +   ```
note the user could already have a custom `LD_LIBRARY_PATH`, so we need to append here, not replace.

2016-09-23 07:02 UTC, rasendubi commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Edison/index.md
> +   ```
@vadimol that's for running application, not compiling.

2016-09-23 07:47 UTC, vadimol commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Edison/index.md
> +   ```
@rasendubi , I meant the "compilation phase". We run avrocpp during the building of the demo and according to logs in http://jira.kaaproject.org/browse/APP-271, it cannot find run-time libraries.
Yes, of course, we also need run-time libraries to run the application.

2016-09-23 07:53 UTC, rasendubi commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Edison/index.md
> +   ```
oh, sorry. haven't read the issue :unamused:

2016-09-26 10:54 UTC, Dubland commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Edison/index.md
> +   ```
Changed

2016-09-26 11:16 UTC, vadimol approved these changes
LGTM

2016-09-26 14:08 UTC, rasendubi commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Edison/index.md
> +Before building your application put this command `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib` in a console for setting directories where libraries should be searched for first.
Prepend, don't append.

Also, enclose in the `"`.

2016-09-26 14:08 UTC, rasendubi requested changes

2016-09-27 14:56 UTC, Dubland commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Edison/index.md
> +Before building your application put this command `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib` in a console for setting directories where libraries should be searched for first.
Changed

2016-09-27 14:59 UTC, rasendubi requested changes
You haven't tested the guide. The `"LD_LIBRARY_PATH"` is a normal string, not variable. Use `"$LD_LIBRARY_PATH"`.

2016-09-27 17:02 UTC, rasendubi approved these changes

2016-09-28 10:35 UTC, vadimol approved these changes
LGTM

2016-09-28 10:35 UTC, merged