KAA-1135: Using Kaa endpoint SDKs - reviewed.
kaaproject/kaa pull request #1101
Opened 2016-09-22 15:41 UTC by hunch7

2016-09-22 23:14 UTC, vadimol commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/index.md
> +Developing a [Kaa instance]({{root_url}}Glossary/#kaa-instance-kaa-deployment) requires following the same routine: creating network communication stack, log delivery functionality, event exchange be
It is unclear to me. I think you've missed the key point of this sentence.
The first version:
_Developing an IoT solution we all the time facing the same routine: creating network communication stack, log delivery functionality, event exchange between endpoints, etc._
means that the typical IoT solution requires implementing of the same routines.

The _Kaa instance_ already provides all of these routines and it does not require them.

2016-09-22 23:15 UTC, vadimol requested changes
Reviewed. Please, take a look.

2016-09-22 23:20 UTC, vadimol commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/index.md
> +Developing a [Kaa instance]({{root_url}}Glossary/#kaa-instance-kaa-deployment) requires following the same routine: creating network communication stack, log delivery functionality, event exchange be
Or, maybe, I just don't understand you correctly.

2016-09-23 10:41 UTC, hunch7 commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/index.md
> +Developing a [Kaa instance]({{root_url}}Glossary/#kaa-instance-kaa-deployment) requires following the same routine: creating network communication stack, log delivery functionality, event exchange be
I think you said the same but in other words, which means your understanding is correct anyway :) All I did there is I changed 'IoT solution' to 'Kaa instance' to be more precise why I mention that 'routine' -- I don't think it's safe to assume it's the same routine for _every_ IoT solution out there.

2016-09-26 14:43 UTC, merged