KAA-1178: Cluster setup guide - reviewed.
kaaproject/kaa pull request #1108
Opened 2016-09-26 15:01 UTC by hunch7

2016-09-27 10:28 UTC, sashadidukh requested changes

2016-09-27 10:28 UTC, sashadidukh commented on doc/Administration-guide/System-installation/Cluster-setup/index.md
> +For database cluster installation, refer to the official [Cassandra](http://docs.datastax.com/en/landing_page/doc/landing_page/current.html), [MongoDB](https://docs.mongodb.com/manual/) and [PostgreS
In our Single node installation guide we use official Apache Cassandra database, so here we should change [Cassandra](http://docs.datastax.com/en/landing_page/doc/landing_page/current.html) to [Cassandra](http://cassandra.apache.org/).

2016-09-27 10:28 UTC, sashadidukh commented on doc/Administration-guide/System-installation/Cluster-setup/index.md
> +MariaDB comes with the master-master replication support out of the box, therefore it is recommended that you use this database in your Kaa cluster.
MariaDB doesn't come with the master-master replication support out of the box. We should remove this sentence.

2016-09-27 14:03 UTC, sashadidukh requested changes

2016-09-27 14:03 UTC, sashadidukh commented on doc/Administration-guide/System-installation/Cluster-setup/index.md
> +In addition to the firewall rules set up during the Kaa node service installation process, you need to add some rules for the databases (depending on the choice of databases in the cluster) and Zooke
Please add:
... you need to add some rules for the databases (depending on the choice of databases in the cluster), Kaa node thrift and Zookeeper ports.

2016-09-27 14:03 UTC, sashadidukh commented on doc/Administration-guide/System-installation/Cluster-setup/index.md
>  $ sudo service iptables-persistent save
Please add before # Zookeeper port section # Kaa node thrift section:

\# Kaa node thrift
$ sudo iptables -I INPUT -p tcp -m tcp --dport 9090 -j ACCEPT
$ sudo iptables -I OUTPUT -p tcp -m tcp --dport 9090 -j ACCEPT

2016-09-27 15:22 UTC, hunch7 commented on doc/Administration-guide/System-installation/Cluster-setup/index.md
> +For database cluster installation, refer to the official [Cassandra](http://docs.datastax.com/en/landing_page/doc/landing_page/current.html), [MongoDB](https://docs.mongodb.com/manual/) and [PostgreS
Fixed.

2016-09-27 15:22 UTC, hunch7 commented on doc/Administration-guide/System-installation/Cluster-setup/index.md
> +MariaDB comes with the master-master replication support out of the box, therefore it is recommended that you use this database in your Kaa cluster.
Done.

2016-09-27 15:22 UTC, hunch7 commented on doc/Administration-guide/System-installation/Cluster-setup/index.md
> +In addition to the firewall rules set up during the Kaa node service installation process, you need to add some rules for the databases (depending on the choice of databases in the cluster) and Zooke
Done.

2016-09-27 15:22 UTC, hunch7 commented on doc/Administration-guide/System-installation/Cluster-setup/index.md
>  $ sudo service iptables-persistent save
Done.

2016-09-28 13:18 UTC, hunch7 commented
New PR: https://github.com/kaaproject/kaa/pull/1119

2016-09-28 13:18 UTC, closed without merging