KAA-1123: Upgrading your instance, 0.9.x to 0.10.x - reviewed.
kaaproject/kaa pull request #1112
Opened 2016-09-26 16:40 UTC by hunch7

2016-09-27 10:29 UTC, Deepnekroz commented on doc/Administration-guide/Upgrading-your-instance/0.9.x-to-0.10.x/index.md
> +		sudo ./upgradeKaa081to090.sh
Filename in command does not match filename from step 2.

2016-09-27 11:58 UTC, vadimol requested changes

2016-09-27 11:58 UTC, vadimol commented on doc/Administration-guide/Upgrading-your-instance/0.9.x-to-0.10.x/index.md
> +2. Download the [upgradeKaa090to0100.sh](https://github.com/kaaproject/kaa/blob/v0.10.0/server/upgrade/data-migration-0.9.0-0.10.0/upgradeKaa090to0100.sh) and [data-migration.jar](http://repository.k
The links are not valid.
1) https://github.com/kaaproject/kaa/blob/v0.10.0/server/upgrade/data-migration-0.9.0-0.10.0/upgradeKaa090to0100.sh

2) http://repository.kaaproject.org/repository/releases/org/kaaproject/kaa/server/upgrade/data-migration/0.10.0/db-migration.one-jar.jar

2016-09-28 13:02 UTC, hunch7 commented on doc/Administration-guide/Upgrading-your-instance/0.9.x-to-0.10.x/index.md
> +		sudo ./upgradeKaa081to090.sh
Fixed.

2016-09-28 13:03 UTC, hunch7 commented on doc/Administration-guide/Upgrading-your-instance/0.9.x-to-0.10.x/index.md
> +2. Download the [upgradeKaa090to0100.sh](https://github.com/kaaproject/kaa/blob/v0.10.0/server/upgrade/data-migration-0.9.0-0.10.0/upgradeKaa090to0100.sh) and [data-migration.jar](http://repository.k
The links will be valid after the build.

2016-09-28 13:21 UTC, hunch7 commented on doc/Administration-guide/Upgrading-your-instance/0.9.x-to-0.10.x/index.md
> +2. Download the [upgradeKaa090to0100.sh](https://github.com/kaaproject/kaa/blob/v0.10.0/server/upgrade/data-migration-0.9.0-0.10.0/upgradeKaa090to0100.sh) and [data-migration.jar](http://repository.k
At least this is what @Kirill380 told me :)

2016-09-30 11:35 UTC, Kirill380 commented
LGTM

2016-09-30 11:38 UTC, Kirill380 commented on doc/Administration-guide/Upgrading-your-instance/0.9.x-to-0.10.x/index.md
> +2. Download the [upgradeKaa090to0100.sh](https://github.com/kaaproject/kaa/blob/master/server/upgrade/data-migration-0.9.0-0.10.0/src/main/resources/scripts/upgradeKaa090to0100.sh) and [data-migratio
Why master? Return to v0.10.0. Link become broken but it is okay, cause we haven't release 0.10 version yet and so there is no such version on GitHub repo.

2016-09-30 11:39 UTC, Kirill380 commented on doc/Administration-guide/Upgrading-your-instance/0.9.x-to-0.10.x/index.md
> +2. Download the [upgradeKaa090to0100.sh](https://github.com/kaaproject/kaa/blob/master/server/upgrade/data-migration-0.9.0-0.10.0/src/main/resources/scripts/upgradeKaa090to0100.sh) and [data-migratio
Why master? Return to v0.10.0. Link become broken but it is okay, cause we haven't release 0.10 version yet and so there is no such version on GitHub repo.

2016-09-30 11:44 UTC, Kirill380 commented on doc/Administration-guide/Upgrading-your-instance/0.9.x-to-0.10.x/index.md
> +2. Download the [upgradeKaa090to0100.sh](https://github.com/kaaproject/kaa/blob/master/server/upgrade/data-migration-0.9.0-0.10.0/src/main/resources/scripts/upgradeKaa090to0100.sh) and [data-migratio
And please rename db-migration.one-jar.jar to data-migration_0.9.0-0.10.0.jar. I have found out recently  that name of artifact changed.

2016-09-30 13:44 UTC, hunch7 commented on doc/Administration-guide/Upgrading-your-instance/0.9.x-to-0.10.x/index.md
> +2. Download the [upgradeKaa090to0100.sh](https://github.com/kaaproject/kaa/blob/master/server/upgrade/data-migration-0.9.0-0.10.0/src/main/resources/scripts/upgradeKaa090to0100.sh) and [data-migratio
Fixed.

2016-10-06 13:19 UTC, Kirill380 commented
LGTM

2016-10-06 14:40 UTC, merged