KAA-1237: Docker deployment improvements
kaaproject/kaa pull request #1113
Opened 2016-09-27 08:59 UTC by chv348

Docker deployment improvements

2016-09-28 07:57 UTC, ashvayka requested changes

2016-09-28 07:57 UTC, ashvayka commented on .gitignore
> +/server/containers/docker/kaa-node.deb
this is strange.. is this a side effect of build? We need to cleanup such files, not ignore. The correct location of all build artifacts is in build (target) folder.

2016-09-28 07:57 UTC, ashvayka commented on server/containers/docker/Dockerfile
> +		mc \
please make sure that all this tools are necessary. No need to waste disk space :-)

2016-09-28 07:57 UTC, ashvayka commented on server/containers/docker/Dockerfile
> +COPY ["$setupfile", "/kaa-node.deb"]
copy this file from build folder.

2016-09-28 07:57 UTC, ashvayka commented on server/containers/docker/Dockerfile
> +RUN touch /var/log/kaa/kaa-node.log \
this is strange. Why do you need this?

2016-09-28 07:57 UTC, ashvayka commented on server/containers/docker/Dockerfile
> +EXPOSE 9090
what is this port about? maybe add some comment or move this to configuration file/constant

2016-09-28 07:57 UTC, ashvayka commented on server/containers/docker/Dockerfile
> +RUN echo 'kaa     ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
why do you need this?

2016-09-28 12:51 UTC, chv348 commented on server/containers/docker/Dockerfile
> +RUN echo 'kaa     ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
you a right. this configuration is unnecessary.

2016-09-29 10:02 UTC, chv348 commented on .gitignore
> +/server/containers/docker/kaa-node.deb
kaa-docker-compose.yml will be creating when you start launch-kaa.sh(script which configure kaa-node and start docker)
if you want download kaa-node.deb from http://www.kaaproject.org/download-kaa/
you can locate this file in /server/containers/docker/ folder and run sh build.sh for creating docker image

2016-09-29 10:02 UTC, chv348 commented on server/containers/docker/Dockerfile
> +		mc \
we don't need vim, curl and mc. fixed.

2016-09-29 10:05 UTC, chv348 commented on server/containers/docker/Dockerfile
> +COPY ["$setupfile", "/kaa-node.deb"]
Command COPY ["$setupfile", "/kaa-node.deb"] get file from build image command and set it in root folder in image. Next command in Dockerfile will install kaa in this image.

2016-09-29 10:06 UTC, chv348 commented on server/containers/docker/Dockerfile
> +EXPOSE 9090
this is default thrift port from property file(kaa-node.properties).

2016-09-29 10:09 UTC, chv348 commented on server/containers/docker/Dockerfile
> +RUN touch /var/log/kaa/kaa-node.log \
When kaa create this file in docker container, service kaa-node can't write logs into this file, because it hasn't any permission to do it.

2016-10-05 07:54 UTC, ashvayka commented on server/containers/README.md
> +1. Download debian package from [official site](http://www.kaaproject.org/download-kaa/)
This step needs to be improved. I suggest to download deb package automatically from https://github.com/kaaproject/kaa/releases (navigate to particular release for more details. relese version should be a configuration parameter with default value equal to current release.

2016-10-05 07:55 UTC, ashvayka commented on server/containers/README.md
> +$ docker build --build-arg setupfile=kaa-node.deb -t kaa-node:0.10.0 .
why do you need a 0.10.0 parameter here? What does this mean?

2016-10-05 07:56 UTC, ashvayka commented on server/containers/README.md
> +$ docker exec -it usingcompose_KAA_SERVICE_NAME_1 /bin/bash -c "export TERM=xterm; exec bash"
what is usingcompose_KAA_SERVICE_NAME_1 ?

2016-10-05 07:58 UTC, ashvayka commented on server/containers/README.md
> +In this example usingcompose - it's name of folder where located docker-compose.yml files.
it is not clear what docker-compose.yml we are talking about. Please clarify this in instruction. I would replace usingcompose_KAA_SERVICE_NAME_1 with something clear (cluster_compose_folder or similar)

2016-10-05 08:01 UTC, ashvayka commented on server/containers/README.md
> +Also you can use some prepared in advance docker-compose files in **docker-compose-1-node** folder.
This should be moved to the top of the instruction. People need to know how to run the working single-node cluster in seconds, not minutes after opening this doc. Place a disclaimer that this is a single node installation, Advanced docker users can follow guide for multi node installations.

2016-10-05 08:01 UTC, ashvayka commented on server/containers/README.md
> +Also you can use some prepared in advance docker-compose files in **docker-compose-1-node** folder.
Please open a dedicated ticket to write an article howto deploy kaa in cluster mode using docker swarm.

2016-10-06 07:20 UTC, chv348 commented
@kaa-leeroy retests this please

2016-10-06 09:12 UTC, merged