KAA-1224: Incorrect calculation of log delivery time
kaaproject/kaa pull request #1132
Opened 2016-10-06 08:59 UTC by mlysenko

2016-10-10 10:14 UTC, ohamov requested changes
Reviewed

2016-10-10 10:14 UTC, GamovCoder commented on client/client-multi/client-cpp/kaa/channel/transport/ILoggingTransport.hpp
> +    virtual void onLogSyncResponse(const LogSyncResponse& response, std::size_t deliveryTime) = 0;
document `deliveryTime` parameter.

2016-10-10 10:14 UTC, GamovCoder commented on client/client-multi/client-cpp/kaa/log/ILogProcessor.hpp
> +    virtual void onLogUploadResponse(const LogSyncResponse& response, std::size_t deliveryTime) = 0;
the same

2016-10-10 10:14 UTC, GamovCoder commented on client/client-multi/client-cpp/test/impl/log/LogCollectorTest.cpp
> +    logCollector.onLogUploadResponse(response, 1);
no magic numbers

2016-10-10 12:00 UTC, vadimol commented
@kaa-leeroy retest this please

2016-10-10 12:19 UTC, ohamov requested changes

2016-10-10 12:19 UTC, GamovCoder commented on client/client-multi/client-cpp/test/impl/log/LogCollectorTest.cpp
> +const std::size_t logDeliveryTime = 1;
I'd rename it to point out that this variable is nothing but the mock and doesn't affect the tests results.

2016-10-10 12:19 UTC, GamovCoder commented on client/client-multi/client-cpp/kaa/channel/transport/ILoggingTransport.hpp
> +     * @param deliveryTime a time when the log was delivered
`s/a time when the log was delivered/The time point the log was delivered at`

2016-10-10 12:19 UTC, GamovCoder commented on client/client-multi/client-cpp/kaa/log/ILogProcessor.hpp
> +     * \param   deliveryTime    Time when the log was delivered.
`s/Time when the log was delivered/The time point the log was delivered at`

2016-10-12 12:50 UTC, mlysenko commented
The PR has been updated. Please review.

2016-10-13 10:21 UTC, vadimol commented
@kaa-leeroy retest this please

2016-10-13 11:23 UTC, ohamov approved these changes
LGTM

2016-10-13 16:42 UTC, vadimol approved these changes
LGTM

2016-10-13 16:42 UTC, merged