KAA-1467: Administration Guide -> Tenant and applications management
kaaproject/kaa pull request #1148
Opened 2016-10-11 14:02 UTC by Pyshankov

2016-10-21 16:56 UTC, akokhanovskyi requested changes

2016-10-21 16:56 UTC, akokhanovskyi commented on doc/Administration-guide/Tenants-and-applications-management/index.md
> +  - [Managing Tenants](#managing-tenants)
Why don't you use the standard TOC generation tag?

2016-10-21 16:56 UTC, akokhanovskyi commented on doc/Administration-guide/Tenants-and-applications-management/index.md
> +This guide explains how to manage develop applications in Kaa Admin UI.
What? This guide is supposed to be about managing tenants and applications.

2016-10-21 16:56 UTC, akokhanovskyi commented on doc/Administration-guide/Tenants-and-applications-management/index.md
>  ## Managing Tenant CTL
CTL is not in scope of this page.

2016-10-25 10:00 UTC, rasendubi commented
@Pyshankov this needs update.

2016-10-26 08:32 UTC, rasendubi commented
@akokhanovskyi please, re-review

2016-10-26 16:39 UTC, akokhanovskyi requested changes

2016-10-26 16:39 UTC, akokhanovskyi commented on doc/Customization-guide/Customizable-system-components/Owner-verifiers/index.md
> +7. Use Admin UI or [REST API]({{root_url}}Programming-guide/Server-REST-APIs/#!/Verifiers/editUserVerifier) to create/update/delete your owner verifier instances.
Administration UI

2016-10-26 16:39 UTC, akokhanovskyi commented on doc/Getting-started/index.md
> +<img src="attach/image2015-5-28%2017-22-54.png" width="700" height="350">
Wrong png

2016-10-26 16:39 UTC, akokhanovskyi commented on doc/Getting-started/index.md
> +<img src="attach/image2015-5-28%2017-26-57.png" width="600" height="400">
Wrong png

2016-10-26 16:39 UTC, akokhanovskyi commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Edison/index.md
>  1. Compile C++ SDK.
2.

2016-10-26 16:39 UTC, akokhanovskyi commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Edison/index.md
> +1. Download C++ SDK.
...from your Kaa instance.

2016-10-26 16:39 UTC, akokhanovskyi commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-RPi/index.md
> +7. Download C++ SDK.
...from your Kaa instance.

2016-10-26 16:39 UTC, akokhanovskyi commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C/SDK-TI-CC3200/index.md
> +To do so, generate the C SDK in Admin UI, then extract the archive.
Administration UI

2016-10-26 17:15 UTC, akokhanovskyi approved these changes

2016-10-26 17:22 UTC, merged