KSF-88: Getting started - fixed upon developer review.
kaaproject/kaa pull request #1161
Opened 2016-10-13 12:55 UTC by hunch7

2016-10-13 18:12 UTC, Slash32 requested changes
I would not recommend dropping whole the TIP part with description of the Network configuration, modes, etc.

Could this be just extended with the information that the Sandbox is now capable of working out of the box (provided the Hostname is correct)?

The main advantage of Bridged is that the Sandbox can detect and apply the Kaa Host correctly. While NAT does not provide such support and is better in other aspects.

2016-10-17 11:35 UTC, hunch7 commented
Fixed.

2016-10-17 13:03 UTC, Slash32 approved these changes

2016-10-18 08:09 UTC, rasendubi commented on doc/Getting-started/index.md
> +	>This enables your host machine to connect to the [Kaa server]({{root_url}}Glossary/#kaa-server).
As far as I know, in current configuration this allows connecting from any machine, not only host.

2016-10-18 08:09 UTC, rasendubi commented on doc/Getting-started/index.md
> +5. Wait until the VirtualBox starts up and open [127.0.0.1:9080/sandbox](http://127.0.0.1:9080/sandbox) URL in your browser.
Does this work for bridged adapter?

2016-10-18 08:39 UTC, hunch7 commented on doc/Getting-started/index.md
> +5. Wait until the VirtualBox starts up and open [127.0.0.1:9080/sandbox](http://127.0.0.1:9080/sandbox) URL in your browser.
No, it doesn't. Actually, the Sandbox console displays a pretty clear message regarding what IP your Sandbox is on, for both NAT and Bridged Adapter, so our dear users won't get lost anyway.

2016-10-18 08:47 UTC, hunch7 commented on doc/Getting-started/index.md
> +	>This enables your host machine to connect to the [Kaa server]({{root_url}}Glossary/#kaa-server).
Fixed.

2016-10-19 08:26 UTC, Slash32 commented on doc/Getting-started/index.md
> +5. Wait until the VirtualBox starts up and open [127.0.0.1:9080/sandbox](http://127.0.0.1:9080/sandbox) URL in your browser.
Actually, Sandbox will work correctly provided it is in Bridged mode and gets rebooted after the IP change. Applications will not work until their SDKs are updated with the new IP address.

What is meant here is that for NAT mode, you will need to also change the Management->Kaa Host manually before downloading SDKs.

2016-10-19 08:26 UTC, Slash32 commented on doc/Getting-started/index.md
> +5. Wait until the VirtualBox starts up and open [127.0.0.1:9080/sandbox](http://127.0.0.1:9080/sandbox) URL in your browser.
Thus, basically, the text presented is correct. It is just not full. But better explanation might be too complex.

2016-10-19 09:07 UTC, rasendubi approved these changes

2016-10-19 09:09 UTC, merged