Feature/kaa 1481
kaaproject/kaa pull request #1166
Opened 2016-10-15 10:48 UTC by Serega290696

2016-10-15 10:48 UTC, kaa-leeroy commented
Can one of the admins verify this patch?

2016-10-17 15:10 UTC, Rib47 commented on client/client-multi/client-java-core/src/main/java/org/kaaproject/kaa/client/context/FlexibleExecutorContext.java
> +            FlexibleExecutorContext f = new FlexibleExecutorContext(this);
You must check builder fields for **null** values. If any **null** value will be found you must throw an exception or  set fields to default values. The second alternative is better one.

2016-10-19 13:35 UTC, Rib47 requested changes
Missed licenses

2016-10-19 13:35 UTC, Rib47 commented on client/client-multi/client-java-core/src/test/java/org/kaaproject/kaa/client/context/FlexibleExecutorContextTest.java
> +package org.kaaproject.kaa.client.context;
missed license in this file
see documentation:
[(https://docs.google.com/document/d/1gesi7pElMnoT5ocefV0qLooEMnZuTvTc81xSdJQGGTI)]

2016-10-19 13:35 UTC, Rib47 commented on client/client-multi/client-java-core/src/test/java/org/kaaproject/kaa/client/context/FlexibleExecutorContextTest.java
> +
missed license in this file
see documentation:
[(https://docs.google.com/document/d/1gesi7pElMnoT5ocefV0qLooEMnZuTvTc81xSdJQGGTI)]

2016-10-20 13:10 UTC, closed without merging