KAA-1397: Update Kaa Sandbox Networking page
kaaproject/kaa pull request #1168
Opened 2016-10-17 15:51 UTC by Acarus

2016-10-21 17:09 UTC, Slash32 approved these changes

2016-10-25 10:01 UTC, rasendubi commented
@Acarus this needs update

2016-10-25 12:26 UTC, Slash32 requested changes
I would prefer to leave the merged variant in place.
Please drop the TIP change and leave here only the doc/Customization-guide/Code-style/Java/index.md part.

2016-10-26 09:01 UTC, rasendubi commented on doc/Customization-guide/Code-style/Java/index.md
> +5. Add the configuration file (`checkstyle.xml`) from root of the Kaa project.
Where `checkstyle.xml` comes from?

2016-10-26 09:47 UTC, Acarus commented on doc/Customization-guide/Code-style/Java/index.md
> +5. Add the configuration file (`checkstyle.xml`) from root of the Kaa project.
`checkstyle.xml` is located in root of the project.  It's google code style rules with some changes.

2016-10-26 09:58 UTC, rasendubi commented on doc/Customization-guide/Code-style/Java/index.md
> +5. Add the configuration file (`checkstyle.xml`) from root of the Kaa project.
Oh, ok. I would insert a link here, but that's minor.

2016-10-26 18:35 UTC, Slash32 approved these changes
LGTM

2016-10-26 22:12 UTC, rasendubi commented
@Acarus, please, resolve conflicts

2016-10-27 12:13 UTC, garniy approved these changes
LGTM

2016-10-27 12:26 UTC, merged