KAA-1160: Glossary - fixed upon AK review.
kaaproject/kaa pull request #1171
Opened 2016-10-17 17:27 UTC by hunch7

2016-10-18 15:22 UTC, akokhanovskyi requested changes

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
A virtual entity that operates within the [actor gateway]({{root_url}}Glossary/#actor-gateway) to impersonate a physical device, virtual object, library, etc. as a Kaa [endpoint]({{root_url}}Glossary/#endpoint).

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
A Kaa-based component that initializes, manages, and uses [actors]({{root_url}}Glossary/#actor) to represent endpoints connected to the gateway.

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
Remove this. It's not only available via Sandbox.

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
Deployments with an actor gateway are intended for IoT environments that use proximity or non-Internet communication protocols, and thus have to be bridged to communicate to the server.

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
A certain version of a [Kaa application]({{root_url}}Glossary/#kaa-application) whose behavior is defined by a specific set of extensions and their configurations.

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
You can copy Application token from the main window of the [Administration UI]({{root_url}}Glossary/#administration-ui).

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
Avro UI forms are used to create Kaa data schemas and data records in the visual environment as opposed to JSON syntax.

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
This link is wrong as this content should not be there is the first place.

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
Kaa clients use a Bootstrap services list for a certain [Kaa instance]({{root_url}}Glossary/#kaa-instance-kaa-deployment) embedded in the SDK.

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
This is misleading (wrong instance term reference etc.). Remove.

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
A versioned data schema structure definition, managed within the [Common type library]({{root_url}}Glossary/#common-type-library-ctl).

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
Also see [Common type library]({{root_url}}Programming-guide/Key-platform-features/Common-type-library) documentation section.

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
See [Common type library]({{root_url}}Programming-guide/Key-platform-features/Common-type-library) documentation section.

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
A repository of [common types]({{root_url}}Glossary/#common-type-ct) that can be reused in Kaa modules.

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
remove

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
remove

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
Wrong. Remove.

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
Replace with:
Kaa represents every managed entity: device, sensor, mobile phone, etc. as an endpoint.

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
Replace with:
An endpoint group is defined by a set of filters against the endpoint profile.
Those endpoints, profiles of which match the filter, get automatically assigned to a group.

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
An isolated set of configurations and code that utilize [Kaa platform]({{root_url}}Glossary/#kaa-platform) functionality for a specific use case.

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
Kaa client typically uses Kaa [endpoint SDK]({{root_url}}Glossary/#endpoint-sdk) to communicate to the [Kaa server]({{root_url}}Glossary/#kaa-server).

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
An independent software module that implements an isolated set of functions aimed at extending the communication capabilities between Kaa server and Kaa clients.

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
remove

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
The Kaa platform comprises [Kaa server]({{root_url}}Glossary/#kaa-server) and [endpoint SDKs]({{root_url}}Glossary/#endpoint-sdk).

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
Currently, there are four SDK types supported in Kaa: Java, C, C++, Objective-C.

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
A particular way of rebalancing the workload between the [Operations services]({{root_url}}Glossary/#operations-service) within a [Kaa cluster]({{root_url}}Glossary/#kaa-cluster) to achieve the desired load for each service.

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
Wrong. It can actually use multiple. Remove.

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
You can [create custom log appenders]({{root_url}}Customization-guide/Customizable-system-components/Log-appenders).

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
remove

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
The operation service is mainly intended for data exchange and synchronization with [endpoints]({{root_url}}Glossary/#endpoint-ep).

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
remove

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
remove

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
A predicate expression based on the Spring Expression Language designed to filter endpoint profiles.
By applying profile filters Kaa platform identifies which endpoints should be attributed to a specific endpoint group.

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
remove

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
A business entity that uses a part or a whole [Kaa instance]({{root_url}}Glossary/#kaa-instance-kaa-deployment) to independently run [Kaa applications]({{root_url}}Glossary/#kaa-application).

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
A set of specific [Kaa platform]({{root_url}}Glossary/#kaa-platform) functionality that is logically integrated and managed as a single system.

2016-10-18 15:22 UTC, akokhanovskyi commented on doc/Glossary/index.md
> -| User verifier                                           | A server component that handles the user verification. Refer to User verifiers for more information.
A component that implements communication between clients and [Kaa server]({{root_url}}Glossary/#kaa-server).

2016-10-19 13:49 UTC, akokhanovskyi approved these changes

2016-10-19 14:48 UTC, hunch7 commented
Fixed as per the comments.

2016-10-19 14:49 UTC, akokhanovskyi approved these changes

2016-10-19 15:33 UTC, merged