KAA-1481: 1-thread callback executor (Java client) causes issue with "nested" callback calls
kaaproject/kaa pull request #1189
Opened 2016-10-24 15:38 UTC by Serega290696

2016-10-24 15:58 UTC, Rib47 requested changes

2016-10-24 15:58 UTC, Rib47 commented on client/client-multi/client-java-core/src/test/java/org/kaaproject/kaa/client/context/FlexibleExecutorContextTest.java
> +    ExecutorService executorService = executorContext.getLifeCycleExecutor();
Add other executor services from context.

2016-10-24 15:58 UTC, Rib47 commented on client/client-multi/client-java-core/src/test/java/org/kaaproject/kaa/client/context/FlexibleExecutorContextTest.java
> +    Assert.assertTrue(executorService.isShutdown());
Add assertion for other executor services from context.

2016-10-25 09:57 UTC, rasendubi commented
@kaa-leeroy retest this please

2016-10-25 10:49 UTC, vtkhir requested changes

2016-10-25 10:49 UTC, vtkhir commented on client/client-multi/client-java-core/src/main/java/org/kaaproject/kaa/client/context/FlexibleExecutorContext.java
> +  public FlexibleExecutorContext(FlexibleExecutorContextBuilder builder) {
Please change the access modifier to _private_ in this constructor

2016-10-25 12:47 UTC, vtkhir approved these changes
LGTM

2016-10-26 08:31 UTC, merged