KAA-1470: [Java SDK] Failover strategy doesn't work correctly
kaaproject/kaa pull request #1200
Opened 2016-10-26 09:43 UTC by Kirill380

…ss to Internet

2016-10-26 13:25 UTC, garniy approved these changes

2016-10-26 14:02 UTC, agulenko commented on client/client-multi/client-java-desktop/src/main/java/org/kaaproject/kaa/client/connectivity/PingConnectivityChecker.java
> -      return InetAddress.getByName(host).isReachable(CONNECTION_TIMEOUT_MS);
Not critical, but why not just:
 try {
        try (Socket soc = new Socket()) {
            soc.connect(new InetSocketAddress(addr, openPort), timeOutMillis);
        }
        return true;
    } catch (IOException ex) {
        return false;
    }

2016-10-26 14:44 UTC, vtkhir approved these changes

2016-10-26 14:48 UTC, garniy approved these changes

2016-10-26 15:03 UTC, akokhanovskyi requested changes

2016-10-26 15:03 UTC, akokhanovskyi commented on server/common/log-shared/src/main/java/org/kaaproject/kaa/server/common/log/shared/avro/gen/RecordHeader.java
> +
This file should not have changed, I suppose

2016-10-26 15:03 UTC, akokhanovskyi commented on client/client-multi/client-java-desktop/src/test/java/org/kaaproject/kaa/client/connectivity/PingConnectivityCheckerTest.java
> +    PingConnectivityChecker pingConnectivityChecker = new PingConnectivityChecker("http://google.com");
This does not match the test name. Please update the test name.

2016-10-26 17:13 UTC, Kirill380 commented on server/common/log-shared/src/main/java/org/kaaproject/kaa/server/common/log/shared/avro/gen/RecordHeader.java
> +
I  separated license from class, this does not affect code, just for pretty look.

2016-10-27 09:25 UTC, agulenko approved these changes

2016-10-27 09:59 UTC, garniy approved these changes

2016-10-27 10:00 UTC, akokhanovskyi approved these changes

2016-10-27 10:00 UTC, merged