KAA-1510 Add Ubuntu 16.04 support
kaaproject/kaa pull request #1238
Opened 2016-11-02 16:57 UTC by GamovCoder

2016-11-02 17:41 UTC, Slash32 requested changes
I would rather make the commands separated by a tabs like it is done on other Documentation pages.

2016-11-02 17:41 UTC, Slash32 commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Linux/index.md
> +   sudo apt-get install g++ cmake python libboost-all-dev libsqlite3-0 libsqlite3-dev
Does this change mean also that for Ubuntu 14.04 libboost-all-dev now refers to libboost1.55-all-dev (or above)?

2016-11-03 10:07 UTC, GamovCoder commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Linux/index.md
> +   sudo apt-get install g++ cmake python libboost-all-dev libsqlite3-0 libsqlite3-dev
No, for Ubuntu 14.04 libboost-all-dev refers to libboost1.54-all-dev. But I'm convinced that [we can build cpp client](https://github.com/kaaproject/kaa/blob/release-0.10/client/client-multi/client-cpp/CMakeLists.txt#L393) using 1.54. Though, thx for the comment, I found that the patch also disables `avrogencpp` build. So, I'm going to change the guide: for Ubuntu 16.04 boost should be built from the source or we should create another patch which disables the tests build for Avro, but doesn't disable avrogencpp build. @Slash32, what option do you think fits better?

2016-11-03 10:28 UTC, vadimol commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Linux/index.md
> +   sudo apt-get install g++ cmake python libboost-all-dev libsqlite3-0 libsqlite3-dev
I wouldn't be so sure regarding boost version. Have you checked that C++ SDK works fine with 1.54?

2016-11-03 18:10 UTC, GamovCoder commented
/cc @Slash32

2016-11-03 19:11 UTC, Slash32 commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Linux/index.md
> +   export LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH}
Doesn't it be better to run ldconfig(8) for this?

2016-11-04 14:41 UTC, ohamov commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Linux/index.md
> +   export LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH}
Is there any advantage of using `ldconfig` instead of `LD_LIBRARY_PATH`?

2016-11-04 15:23 UTC, Slash32 commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Linux/index.md
> +   export LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH}
Yes, ldconfig has system-wide effect including already running processes and environments.
And the 'export' way affects only the environment (process) this was done in and is dropped with its exit.

2016-11-07 12:43 UTC, vadimol approved these changes

2016-11-08 10:57 UTC, rasendubi commented
Manually installing to `/usr` is bad. It's controlled by the system package manager, so it may come as a surprise to it. (And all kind of bad things could happen.)

2016-11-14 10:47 UTC, rasendubi commented
@GamovCoder, please revert to the previous version and add `ldconfig` call along with a short explanation why it's needed. (It might be good to keep both versions if we explain the difference, but that's up to you.)

2016-11-14 12:19 UTC, rasendubi commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Linux/index.md
> +   sudo ln -s /usr/include/botan-1.11/botan /usr/include/botan
Please sync with #1244.

2016-11-14 12:19 UTC, rasendubi commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Linux/index.md
> +5. Update links to libraries:
Expand little on what `ldconfig` does.

2016-11-14 12:42 UTC, GamovCoder commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Linux/index.md
> +   sudo ln -s /usr/include/botan-1.11/botan /usr/include/botan
removed the line, guess my request should merged after the one you mentioned

2016-11-14 12:43 UTC, GamovCoder commented
/cc @rasendubi

2016-11-14 12:44 UTC, vadimol commented
Merged related requests

2016-11-14 13:51 UTC, rasendubi approved these changes

2016-11-14 13:52 UTC, merged

2016-11-14 13:52 UTC, rasendubi commented
@GamovCoder, please, backport to master.