Corrected FindBotan.cmake and doc to search in default path
kaaproject/kaa pull request #1244
Opened 2016-11-03 15:58 UTC by sparadiuk

2016-11-03 20:04 UTC, rasendubi requested changes

2016-11-03 20:04 UTC, rasendubi commented on client/client-multi/client-cpp/Modules/FindBotan.cmake
> +        set(BOTAN_LIBRARY_NAMES ${BOTAN_LIBRARY_NAMES} ${BOTAN_VERSION_NAME})
Don't like this line. `BOTAN_VERSION_NAME` is for directory name, it's just a coincidence the library is named the same way.

2016-11-03 20:04 UTC, rasendubi commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Beaglebone/index.md
> -        ln -s botan-1.11/botan/ "${SYSROOT}"/include/botan
```
rasen@Larry ~/p/kaa> grep botan-1.11 . -R | some-hand-sorting
./client/client-multi/client-cpp/tools/build_sdk_thirdparty.bat:  move %ROOT_PATH%/include/botan-1.11/botan %ROOT_PATH%/include
./client/client-multi/client-cpp/docs/qnx/INSTALL:ln -s $KAA_THIRDPARTY_HOME/include/botan-1.11/botan $KAA_THIRDPARTY_HOME/include/botan
./doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Linux/index.md:   sudo ln -s /usr/local/include/botan-1.11/botan /usr/local/include/botan
./doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-RPi/index.md:        cp -r ${INSTALLDIR}/include/botan-1.11/botan/ ${INSTALLDIR}/include
./doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-RPi/index.md:        rm -r ${INSTALLDIR}/include/botan-1.11
./doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Edison/index.md:   ln -s /usr/local/include/botan-1.11/botan /usr/local/include/botan
./doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Edison/index.md:        ln -rs ${SDKTARGETSYSROOT}/usr/include/botan-1.11/botan ${SDKTARGETSYSROOT}/usr/include/botan
./doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Samsung-Artik-5/index.md:        ln -s "${INSTALLDIR}"/include/botan-1.11/botan/ "${INSTALLDIR}"/include/botan
```

2016-11-04 23:02 UTC, rasendubi commented on client/client-multi/client-cpp/Modules/FindBotan.cmake
> +    ${BOTAN_VERSION_NAME}/botan/version.h
What's `BOTAN_VERSION_NAME`?

2016-11-04 23:02 UTC, rasendubi commented on client/client-multi/client-cpp/Modules/FindBotan.cmake
> +        set(BOTAN_LIBRARY_NAMES ${BOTAN_LIBRARY_NAMES} ${BOTAN_LIB}.a)
I think this might break something. (It considers fewer alternatives.)

2016-11-04 23:02 UTC, rasendubi commented on client/client-multi/client-cpp/Modules/FindBotan.cmake
> +set(BOTAN_CODE_VERSION botan-1.11)
I would like to use something like
```
set(BOTAN_VERSION 1.11)
```

And use this variable later on.

2016-11-08 10:53 UTC, rasendubi commented
What's ticket number for this?

2016-11-08 11:49 UTC, sparadiuk commented on client/client-multi/client-cpp/Modules/FindBotan.cmake
> +set(BOTAN_CODE_VERSION botan-1.11)
It tried to use it BOTAN_VERSION before, but it has an error, looks like CMake has it.
I propose use set(BOTAN_VERSION_CODE 1.11)

2016-11-09 15:32 UTC, rasendubi commented on client/client-multi/client-cpp/Modules/FindBotan.cmake
> +set(BOTAN_CODE_VERSION botan-1.11)
Can we reuse cmake's variable?

2016-11-11 09:14 UTC, vadimol requested changes
@sparadiuk , please, address comments

2016-11-11 10:29 UTC, sparadiuk commented on client/client-multi/client-cpp/Modules/FindBotan.cmake
> +set(BOTAN_CODE_VERSION botan-1.11)
I think no,  they have a full version, for an example BOTAN_VERSION is 1.11.28

2016-11-11 15:10 UTC, sparadiuk commented on client/client-multi/client-cpp/Modules/FindBotan.cmake
> +    ${BOTAN_VERSION_NAME}/botan/version.h
It was a define for botan-1.11 version. Have changed

2016-11-11 15:35 UTC, sparadiuk commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Beaglebone/index.md
> -        ln -s botan-1.11/botan/ "${SYSROOT}"/include/botan
Changed

2016-11-11 15:35 UTC, sparadiuk commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Beaglebone/index.md
> -        ln -s botan-1.11/botan/ "${SYSROOT}"/include/botan
in all

2016-11-11 15:40 UTC, sparadiuk commented
Changed

2016-11-11 15:44 UTC, sparadiuk commented on client/client-multi/client-cpp/Modules/FindBotan.cmake
> +        set(BOTAN_LIBRARY_NAMES ${BOTAN_LIBRARY_NAMES} ${BOTAN_VERSION_NAME})
Changed to BOTAN_CODE_VERSION

2016-11-11 15:45 UTC, sparadiuk commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C++/SDK-Beaglebone/index.md
> -        ln -s botan-1.11/botan/ "${SYSROOT}"/include/botan
Changed all

2016-11-11 16:19 UTC, rasendubi commented on client/client-multi/client-cpp/Modules/FindBotan.cmake
> +message(STATUS "Include directory: ${BOTAN_INCLUDE_DIR}")
Debug log left.

2016-11-11 16:24 UTC, sparadiuk commented on client/client-multi/client-cpp/Modules/FindBotan.cmake
> +message(STATUS "Include directory: ${BOTAN_INCLUDE_DIR}")
have removed

2016-11-11 16:34 UTC, rasendubi approved these changes
good to merge. @vadimol please ensure this one is properly tested (including building botan in static)

2016-11-14 11:53 UTC, vadimol approved these changes

2016-11-14 12:44 UTC, merged