KAA-1571: Introduce CMake toolchain file for Intel Edison platform.
kaaproject/kaa pull request #1251
Opened 2016-11-09 11:22 UTC by RostakaGmfun

This commit also slightly corrects this toolchain file.

/cc @Slash32 @vadimol

2016-11-09 13:07 UTC, Slash32 requested changes

2016-11-09 13:07 UTC, Slash32 commented on client/client-multi/client-cpp/toolchains/edison.cmake
> +            set(EDISON_SDK_ROOT C:/Edison/poky-edison-eglibc-i686-edison-image-core2-32-toolchain-1.7.2)
This should be better done with use of Environment variables to allow users to change the place.

2016-11-09 13:07 UTC, Slash32 commented on client/client-multi/client-cpp/toolchains/edison.cmake
> +            set(EDISON_SDK_ROOT C:/Edison/poky-edison-eglibc-x86_64-edison-image-core2-32-toolchain-1.7.2)
Same as above

2016-11-09 13:07 UTC, Slash32 commented on client/client-multi/client-cpp/toolchains/edison.cmake
> +        set(EDISON_SDK_ROOT /opt/poky-edison/1.6)
Same as above

2016-11-09 13:07 UTC, Slash32 commented on client/client-multi/client-cpp/toolchains/edison.cmake
>  		set(CMAKE_MAKE_PROGRAM "C:/Program Files (x86)/mingw/i686-4.9.2-posix-dwarf-rt_v3-rev1/mingw32/bin/mingw32-make.exe")
Same as above

2016-11-09 13:07 UTC, Slash32 commented on client/client-multi/client-c/toolchains/edison.cmake
> +    #Windows host
Indentation issue

2016-11-09 13:07 UTC, Slash32 commented on client/client-multi/client-c/toolchains/edison.cmake
> +		set(CMAKE_MAKE_PROGRAM "C:/Program Files/mingw/i686-4.9.2-posix-dwarf-rt_v3-rev1/mingw32/bin/mingw32-make.exe")
Please use Environment variables for this (see comments below).

2016-11-09 13:07 UTC, Slash32 commented on client/client-multi/client-c/toolchains/edison.cmake
> +		set(CMAKE_MAKE_PROGRAM "C:/Program Files (x86)/mingw/i686-4.9.2-posix-dwarf-rt_v3-rev1/mingw32/bin/mingw32-make.exe")
Same as above

2016-11-09 13:07 UTC, Slash32 commented on client/client-multi/client-c/toolchains/edison.cmake
> +set(CMAKE_SYSTEM_VERSION 3.10.17-poky-edison+)
Please ensure this version is also stated in the documentation.

2016-11-10 08:12 UTC, RostakaGmfun commented on client/client-multi/client-c/toolchains/edison.cmake
> +    #Windows host
Don't see anything wrong

2016-11-10 08:13 UTC, RostakaGmfun commented on client/client-multi/client-cpp/toolchains/edison.cmake
> +            set(EDISON_SDK_ROOT C:/Edison/poky-edison-eglibc-x86_64-edison-image-core2-32-toolchain-1.7.2)
Done

2016-11-10 08:13 UTC, RostakaGmfun commented on client/client-multi/client-cpp/toolchains/edison.cmake
> +        set(EDISON_SDK_ROOT /opt/poky-edison/1.6)
Done

2016-11-11 09:26 UTC, vadimol requested changes

2016-11-11 09:26 UTC, vadimol commented on client/client-multi/client-c/toolchains/edison.cmake
> +if(WIN32)
Have you tested this on Windows platform?

2016-11-11 13:03 UTC, RostakaGmfun commented on client/client-multi/client-c/toolchains/edison.cmake
> +set(CMAKE_SYSTEM_VERSION 3.10.17-poky-edison+)
Done

2016-11-11 13:09 UTC, RostakaGmfun commented on client/client-multi/client-c/toolchains/edison.cmake
> +if(WIN32)
Nope.

2016-11-11 13:41 UTC, vadimol commented on client/client-multi/client-c/toolchains/edison.cmake
> +if(WIN32)
Then remove all the code that relates to Windows support. Let's avoid committing the code that does not work.

2016-11-11 13:41 UTC, vadimol requested changes
See comment

2016-11-11 13:43 UTC, RostakaGmfun commented on client/client-multi/client-c/toolchains/edison.cmake
> +if(WIN32)
Great idea!

2016-11-14 10:16 UTC, vadimol requested changes
One minor nitpick. Overall looks good.

2016-11-14 10:16 UTC, vadimol commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C/SDK-Edison/index.md
> +        cmake -DKAA_MAX_LOG_LEVEL=3 -DCMAKE_TOOLCHAIN_FILE=../libs/kaa/toolchains/edison.cmake ..
Why libs/kaa? We should not assume that user compiles our sample application.

2016-11-14 10:57 UTC, rasendubi reviewed
Check code style. Also, why toolchains for C and C++ SDKs are different?

I wonder if we can merge them into a single file. (I know that's hard now, but we should think about that in the future.)

2016-11-14 10:57 UTC, rasendubi commented on client/client-multi/client-c/toolchains/edison.cmake
> +	set(SDK_32bits FALSE)
Use spaces, not tabs.

2016-11-14 10:57 UTC, rasendubi commented on client/client-multi/client-c/toolchains/edison.cmake
> +if(NOT EXISTS "$ENV{EDISON_SDK_ROOT}")
We prefer CMake variable over environment variables.

2016-11-14 10:57 UTC, rasendubi commented on client/client-multi/client-c/toolchains/edison.cmake
> +else(NOT EXISTS "$ENV{EDISON_SDK_ROOT}")
Don't put condition in `else()` and `endif()` macros.

2016-11-14 10:57 UTC, rasendubi commented on client/client-multi/client-c/toolchains/edison.cmake
> +SET(CMAKE_C_FLAGS "-Os -g3 -Wall --sysroot=${CMAKE_SYSROOT} -m32 -march=i586 -ffunction-sections -fdata-sections"  CACHE STRING "" FORCE)
`-Os -g3 -Wall` do not belong here.

2016-11-14 10:57 UTC, rasendubi commented on client/client-multi/client-c/toolchains/edison.cmake
> +SET(CMAKE_CXX_FLAGS "-Os -g3 -Wall --sysroot=${CMAKE_SYSROOT} -m32 -march=i586 -ffunction-sections -fdata-sections"  CACHE STRING "" FORCE)
`-Os -g3 -Wall` do not belong here.

2016-11-14 10:57 UTC, rasendubi commented on client/client-multi/client-c/toolchains/edison.cmake
> +INCLUDE_DIRECTORIES(${CMAKE_SYSROOT}/usr/include)
Use lower-case for macro names.

2016-11-15 16:13 UTC, rasendubi reviewed
Otherwise, looks good.

2016-11-15 16:13 UTC, rasendubi commented on client/client-multi/client-c/toolchains/edison.cmake
> +if(${SDK_32bits})
Avoid double-expansion.
```cmake
if(SDK_32bits)
```

2016-11-15 16:13 UTC, rasendubi commented on client/client-multi/client-cpp/toolchains/edison.cmake
> +    if(${SDK_32bits})
See comment above.

2016-11-15 16:18 UTC, rasendubi approved these changes

2016-11-17 11:45 UTC, vadimol approved these changes

2016-11-17 14:52 UTC, merged