KAA-1555. Fix issue with sending mail if forgot password
kaaproject/kaa pull request #1257
Opened 2016-11-11 14:58 UTC by Kirill380

2016-11-14 11:16 UTC, rasendubi commented on server/node/src/main/java/org/kaaproject/kaa/server/admin/services/messaging/MessagingServiceImpl.java
> +    // retrieve this data from DB instead of kaa-node property file ; TODO refactor
TODOs without a ticket are not allowed.

2016-11-14 11:16 UTC, rasendubi commented on server/node/src/main/java/org/kaaproject/kaa/server/admin/services/messaging/MessagingServiceImpl.java
> +   * @param email    the email
Could you improve the doc or remove it altogether. (It is stupid and just wastes developers' time.)

2016-11-14 11:16 UTC, rasendubi commented on server/node/src/main/java/org/kaaproject/kaa/server/admin/services/messaging/MessagingServiceImpl.java
> +    String paramsUrl = "";
StringBuilder?

2016-11-14 11:16 UTC, rasendubi commented on server/node/src/main/java/org/kaaproject/kaa/server/admin/services/messaging/MessagingServiceImpl.java
> +  * execution of code on server side.
How it does that?

2016-11-14 11:16 UTC, rasendubi commented on server/node/src/main/java/org/kaaproject/kaa/server/admin/services/entity/gen/GeneralProperties.java
> +
> Autogenerated by Avro
>
> DO NOT EDIT DIRECTLY

2016-11-15 14:58 UTC, Kirill380 commented on server/node/src/main/java/org/kaaproject/kaa/server/admin/services/messaging/MessagingServiceImpl.java
> +  * execution of code on server side.
Because this class is written on js and one can be interpreted on java server

2016-11-15 15:02 UTC, Kirill380 commented on server/node/src/main/java/org/kaaproject/kaa/server/admin/services/messaging/MessagingServiceImpl.java
> +    // retrieve this data from DB instead of kaa-node property file ; TODO refactor
Ok, I will create the appropriate ticket

2016-11-15 15:19 UTC, Kirill380 commented on server/node/src/main/java/org/kaaproject/kaa/server/admin/services/entity/gen/GeneralProperties.java
> +
just a typo)

2016-11-15 15:32 UTC, rasendubi commented on server/node/src/main/java/org/kaaproject/kaa/server/admin/services/messaging/MessagingServiceImpl.java
> +  * execution of code on server side.
The details should be included in the code comment, as many code readers may have the same question.

2016-11-16 09:17 UTC, garniy approved these changes

2016-11-16 12:04 UTC, vtkhir requested changes

2016-11-16 12:04 UTC, vtkhir commented on server/node/src/main/java/org/kaaproject/kaa/server/admin/services/messaging/MessagingServiceImpl.java
> +    for (String key : paramsMap.keySet()) {
Please use Map.entrySet instead

2016-11-16 12:55 UTC, vtkhir approved these changes

2016-11-16 14:24 UTC, merged