KAA-1557: C SDK documentation issue
kaaproject/kaa pull request #1270
Opened 2016-11-15 15:27 UTC by mlysenko

Added a requirement to install cmoka to C SDK docs.

2016-11-16 14:36 UTC, rasendubi commented
Do we need Maven to build SDK with tests?

2016-11-16 14:54 UTC, mlysenko commented
As a client team, we don't. This change was requested by the server team. They use maven to build the whole Kaa (server, clients, etc.). The maven building failed without cmoka installed so @vadimol agreed to add it.

2016-11-16 15:12 UTC, rasendubi commented
I mean we can disable testing in the maven build, so cmocka won't be needed.

2016-11-16 15:14 UTC, vadimol commented
We can do so by passing -DskipTests. We compile and run tests by default

2016-11-16 15:14 UTC, rasendubi commented
ok

2016-11-16 15:19 UTC, rasendubi requested changes

2016-11-16 15:19 UTC, rasendubi commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C/SDK-Linux/index.md
> +To build C SDK with Maven or to run unit tests, the cmoka unit testing framework has to be install as well:
s/cmoka/cmocka
s/install/installed

2016-11-16 15:19 UTC, rasendubi commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C/SDK-Linux/index.md
> +sudo apt-get install libcmocka0 libcmoka-dev
s/libcmoka/libcmocka

2016-11-17 07:24 UTC, mlysenko commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C/SDK-Linux/index.md
> +sudo apt-get install libcmocka0 libcmoka-dev
My bad, thanks

2016-11-17 09:35 UTC, rasendubi approved these changes

2016-11-17 09:40 UTC, merged