KAA-1563: 'Create new version' button doesn't work in the System CTL
kaaproject/kaa pull request #1280
Opened 2016-11-16 16:42 UTC by Pyshankov

2016-11-16 16:49 UTC, vtkhir requested changes

2016-11-16 16:49 UTC, vtkhir commented on server/node/src/main/java/org/kaaproject/kaa/server/admin/client/mvp/activity/CtlSchemaActivity.java
> +import static org.kaaproject.kaa.common.dto.ctl.CTLSchemaScopeDto.SYSTEM;
Please remove unused import

2016-11-16 19:16 UTC, Pyshankov commented
@vtkhir, review please.

2016-11-17 10:57 UTC, vtkhir approved these changes

2016-11-17 11:33 UTC, garniy approved these changes

2016-11-17 11:43 UTC, merged