KAA-1509: Your first Kaa application - fixed.
kaaproject/kaa pull request #1296
Opened 2016-11-17 16:49 UTC by hunch7

'Administration' changed to 'Administration UI'.

2016-11-18 09:59 UTC, vadimol requested changes

2016-11-18 09:59 UTC, vadimol commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +		Build the application by running the following command from the **demo_app** directory.
Why have you removed the line where slf4j-simple-1.7.21.jar is downloaded? Without this file, the Java application won't work correctly.

2016-11-18 13:28 UTC, hunch7 commented on doc/Programming-guide/Your-first-Kaa-application/index.md
> +		Build the application by running the following command from the **demo_app** directory.
My bad, fixed.

2016-11-18 14:38 UTC, vadimol approved these changes

2016-11-21 10:28 UTC, vadimol commented
Travis fail is not related.

2016-11-21 10:28 UTC, merged