APP-478: [C] Add send_event function in header file
kaaproject/kaa pull request #1324
Opened 2016-11-23 16:23 UTC by Dubland

/cc @vadimol @Slash32

2016-11-24 22:12 UTC, GamovCoder commented on client/client-multi/client-c/src/extensions/event/kaa_event.h
> + * It is not recommended to use this function directly. Instead you should use
What about this comment?

2016-11-25 00:13 UTC, Dubland commented on client/client-multi/client-c/src/extensions/event/kaa_event.h
> + * It is not recommended to use this function directly. Instead you should use
We do not use this function directly, but it is called in generated files.

2016-11-25 09:34 UTC, vadimol commented on client/client-multi/client-c/src/extensions/event/kaa_event.h
> + * It is not recommended to use this function directly. Instead you should use
This looks odd.

2016-11-25 12:01 UTC, ohamov requested changes
That's not the right solution. As the comment states, the function should not be used directly and it is not a part of the interface. The function declaration resides in `kaa_event_private.h`. Just add the necessary include to `kaa_event_families.cvm`.

2016-11-30 15:25 UTC, vadimol approved these changes

2016-11-30 15:31 UTC, ohamov approved these changes

2016-11-30 15:31 UTC, vadimol commented
Jenkins failure is not related.

2016-11-30 15:32 UTC, merged