KAA-1578: File system log appender - reviewed.
kaaproject/kaa pull request #1334
Opened 2016-11-28 14:44 UTC by hunch7

2016-11-28 15:45 UTC, Polinaa requested changes

2016-11-28 15:45 UTC, Polinaa commented on doc/Programming-guide/Key-platform-features/Data-collection/File-system-log-appender/index.md
> +Alternatively, you can use the [server REST API]({{root_url}}Programming-guide/Server-REST-APIs/#!/Logging/editLogAppender) to create or edit your Couchbase log appender.
File system

2016-11-28 15:45 UTC, Polinaa commented on doc/Programming-guide/Key-platform-features/Data-collection/File-system-log-appender/index.md
> +To play around with the the Couchbase log appender:
File system log appender

2016-11-29 09:27 UTC, hunch7 commented on doc/Programming-guide/Key-platform-features/Data-collection/File-system-log-appender/index.md
> +To play around with the the Couchbase log appender:
Fixed.

2016-11-29 09:27 UTC, hunch7 commented on doc/Programming-guide/Key-platform-features/Data-collection/File-system-log-appender/index.md
> +Alternatively, you can use the [server REST API]({{root_url}}Programming-guide/Server-REST-APIs/#!/Logging/editLogAppender) to create or edit your Couchbase log appender.
Fixed.

2016-11-29 09:28 UTC, hunch7 reviewed
Fixed upon QA review.

2016-11-29 09:54 UTC, Polinaa approved these changes

2016-11-29 17:40 UTC, vadimol commented
Jenkins and Travis fails are not related.

2016-11-29 17:40 UTC, vadimol approved these changes

2016-11-29 17:40 UTC, merged