KAA-1631 Expand connection info
kaaproject/kaa pull request #1366
Opened 2016-12-07 18:04 UTC by GamovCoder

The patch adds the ability to find out that
an endpoint is connected to a server and the server
has accepted endpoint's credentials.

2016-12-07 18:08 UTC, GamovCoder commented
/cc @rasendubi @RostakaGmfun @yverzun

2016-12-07 19:40 UTC, yverzun approved these changes
LGTM

2016-12-07 19:53 UTC, RostakaGmfun approved these changes
Minor nitpick, otherwise LGTM

2016-12-07 19:53 UTC, RostakaGmfun commented on client/client-multi/client-cpp/kaa/EndpointConnectionInfo.hpp
> +    EndpointConnectionInfo() = default;
I think it is a good idea to initialize members to some default values in this case

2016-12-07 22:14 UTC, rasendubi requested changes

2016-12-07 22:14 UTC, rasendubi commented on client/client-multi/client-cpp/kaa/EndpointConnectionInfo.hpp
> +    bool connectionAccepted_;
Changes the structure layout, thus it's not binary compatible—can't go into the patch release.

2016-12-07 22:16 UTC, rasendubi commented
@GamovCoder consult `Fix Version` field before opening a PR. (Don't close this one—change the branch and re-push.)

2016-12-08 10:05 UTC, GamovCoder commented on client/client-multi/client-cpp/kaa/EndpointConnectionInfo.hpp
> +    bool connectionAccepted_;
Yep, I know. The another way to implement this leads to breaking interfaces. So, I've chosen this way.

2016-12-08 10:08 UTC, ohamov commented on client/client-multi/client-cpp/kaa/EndpointConnectionInfo.hpp
> +    EndpointConnectionInfo() = default;
They have default constructors

2016-12-08 14:36 UTC, GamovCoder commented
/сс @rasendubi

2016-12-08 20:12 UTC, rasendubi approved these changes

2016-12-09 11:59 UTC, rasendubi commented
Jenkins failure is caused by KAA-1640.

2016-12-09 11:59 UTC, merged