KAA-1650: Don't set the body present flag in extension options if body size is equal to zero
kaaproject/kaa pull request #1369
Opened 2016-12-08 12:44 UTC by RostakaGmfun

/cc @GamovCoder @sergio-dev

2016-12-08 12:56 UTC, garniy submitted a review, later dismissed

2016-12-08 13:14 UTC, vtkhir requested changes

2016-12-08 13:14 UTC, vtkhir commented on server/common/server-shared/src/main/java/org/kaaproject/kaa/server/sync/platform/BinaryEncDec.java
> +        && configurationSync.getConfDeltaBody().array().length != 0;
Call [hasArray()](https://docs.oracle.com/javase/8/docs/api/java/nio/ByteBuffer.html#hasArray--) method before invoking [array()](https://docs.oracle.com/javase/8/docs/api/java/nio/ByteBuffer.html#array--)

2016-12-08 13:35 UTC, RostakaGmfun commented
/cc @vtkhir

2016-12-08 14:25 UTC, vtkhir requested changes

2016-12-08 14:25 UTC, vtkhir commented on server/common/server-shared/src/main/java/org/kaaproject/kaa/server/sync/platform/BinaryEncDec.java
> +    boolean confSchemaPresent = configurationSync.getConfSchemaBody() != null
Please extract `configurationSync.getConfSchemaBody()` to local variable

2016-12-08 14:25 UTC, vtkhir commented on server/common/server-shared/src/main/java/org/kaaproject/kaa/server/sync/platform/BinaryEncDec.java
> +    boolean confBodyPresent = configurationSync.getConfDeltaBody() != null
Please extract `configurationSync.getConfDeltaBody()` to local variable

2016-12-08 14:25 UTC, vtkhir commented on server/common/server-shared/src/main/java/org/kaaproject/kaa/server/sync/platform/BinaryEncDec.java
> +        && configurationSync.getConfDeltaBody().array().length != 0;
Fix the typo

2016-12-09 16:54 UTC, vtkhir approved these changes

2016-12-09 17:03 UTC, rasendubi commented
Jenkins failure is caused by KAA-1640 and is not related to the PR.

2016-12-09 17:03 UTC, merged