KAA-1627: added Linux guide for flashing CC32XX
kaaproject/kaa pull request #1427
Opened 2017-01-13 13:26 UTC by yverzun

2017-01-13 14:55 UTC, ohamov requested changes

2017-01-13 14:55 UTC, GamovCoder commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C/SDK-TI-CC3200/index.md
> +Then install UniFlash for [Linux](http://software-dl.ti.com/dsps/forms/self_cert_export.html?prod_no=uniflash_3.4.1.00012_linux.tar.gz&ref_url=http://software-dl.ti.com/ccs/esd/uniflash/) or [Windows
The Item is called **Flashing (Windows only)**, but you're describing both linux and windows flashing

2017-01-13 14:55 UTC, GamovCoder commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C/SDK-TI-CC3200/index.md
> +Then install UniFlash for [Linux](http://software-dl.ti.com/dsps/forms/self_cert_export.html?prod_no=uniflash_3.4.1.00012_linux.tar.gz&ref_url=http://software-dl.ti.com/ccs/esd/uniflash/) or [Windows
Omit 'Then'

2017-01-13 14:55 UTC, GamovCoder commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C/SDK-TI-CC3200/index.md
> +If you are using Linux you'll need to permit execution of installation file (name of file may differ from your's):
`s/you'll/you`

2017-01-13 14:55 UTC, GamovCoder commented on doc/Programming-guide/Using-Kaa-endpoint-SDKs/C/SDK-TI-CC3200/index.md
> +If you are using Linux you'll need to permit execution of installation file (name of file may differ from your's):
`s/installation file/the installation file`
`s/name of file/the name of the file`
Of course, the name of the file differs from the user's one. Though It is not clear whether the name of user's installation file can be a different one. Rephrase this.

2017-01-16 09:02 UTC, ohamov approved these changes

2017-01-16 15:55 UTC, RostakaGmfun approved these changes
LGTM

2017-01-16 15:56 UTC, merged