APP-142: [C] Disable check C++ compiler
kaaproject/kaa pull request #1433
Opened 2017-01-17 17:19 UTC by Dubland

/cc @vadimol

2017-01-17 17:22 UTC, rasendubi commented on client/client-multi/client-c/toolchains/esp8266.cmake
> +cmake_force_cxx_compiler(/bin/false GNU)
Set `"xtensa-lx106-elf-g++${CMAKE_EXECUTABLE_SUFFIX}"` here.

2017-01-18 11:45 UTC, vadimol requested changes

2017-01-18 11:45 UTC, vadimol commented on client/client-multi/client-c/toolchains/esp8266.cmake
> +cmake_force_cxx_compiler(${ESP8266_TOOLCHAIN_PATH}/bin/${XTENSA_G++_COMPILER} GNU)
${XTENSA_G++_COMPILER} -> ${XTENSA_GXX_COMPILER}

2017-01-18 14:57 UTC, vadimol approved these changes

2017-01-18 15:53 UTC, merged