CI-26: Integrate documentation build and links check into CI process
kaaproject/kaa pull request #1490
Opened 2017-02-23 15:23 UTC by RostakaGmfun

/cc @balldir

2017-02-23 15:33 UTC, RostakaGmfun commented
@kaa-leeroy test this please

2017-02-23 17:08 UTC, balldir approved these changes

2017-02-28 17:48 UTC, Slash32 requested changes
This file originates from Jekver project now and thus should be modified there. Otherwise it will be replaced during documentation compilation phase leading to unexpected behavior.

2017-02-28 17:50 UTC, Slash32 approved these changes
Approved upon local discussion.

2017-03-01 14:01 UTC, merged