Simple HBase Log Appender implementation
kaaproject/kaa pull request #1535
Opened 2018-03-24 00:31 UTC by JoaoRei

Hey, 
This is a simple HBase Log Appender implementation, based on Cassandra Log Appender.
It was developed with HBase-0.98.6 and it was used in my master thesis project. 

It provides a simple way to integrate Kaa in an Hadoop Distributed File System (HDFS) through HBase database.

2018-03-24 00:51 UTC, JoaoRei commented
The corresponding Jira Issue is:
KAA-1779 - A simple HBase Log Appender Implementation that provides the integration of Kaa Platform with Hadoop Distributed File System (HDFS) through HBase Log Appender

2018-03-24 16:07 UTC, rasendubi reviewed
Hi, @JoaoRei! Thanks for the patch!

1. The build failure is not related to your changes and is safe to ignore.
2. Please check the code style. It is inconsistent (mixed tabs and spaces, wrong indentation levels, etc.) You can find more info here: http://kaaproject.github.io/kaa/docs/v0.10.0/How-to-contribute/Code-style/Java/

2018-03-25 01:22 UTC, JoaoRei commented
Hi @rasendubi! 
Thanks for your reply! 

I made the changes in the code style to match the Google Java Style as it is stated in the documentation link you sent me. 
Hope everything is alright now

2018-03-28 08:06 UTC, sashadidukh requested changes

2018-03-28 08:06 UTC, sashadidukh commented on server/appenders/hbase-appender/pom.xml
> +			<version>0.98.6-hadoop2</version>
Here and below please use [Dependency Management](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Management) to specify dependencies versions. See example in the 
[appenders](https://github.com/kaaproject/kaa/tree/master/server/appenders).

2018-03-28 08:06 UTC, sashadidukh commented on server/appenders/hbase-appender/pom.xml
> +			</plugin>  -->
Uncomment this configuration.

2018-03-28 08:06 UTC, sashadidukh commented on server/appenders/hbase-appender/pom.xml
> +				<version>1.7.7</version>
We are commonly using the Avro version specified [here](https://github.com/kaaproject/kaa/blob/master/pom.xml#L62).
Let's use `<version>${avro.version}</version>` instead of `<version>1.7.7</version>`.

2018-03-28 08:06 UTC, sashadidukh commented on server/appenders/hbase-appender/src/main/avro/HBaseAppenderConfiguration.avsc
> +				    				"PREFIX_TREE"
Could you apply vertical alignment to this file?

2018-03-28 08:06 UTC, sashadidukh commented on server/appenders/hbase-appender/src/main/java/org/kaaproject/kaa/server/appenders/hbase/appender/HBaseLogEventDao.java
> +      LOG.error("Ops!", e);
Better to provide the more detailed error message. For example, as you do it [here](https://github.com/kaaproject/kaa/pull/1535/files#diff-7a33576c234dd437a767a6a0876b11d4R169).

Also, it's not allowed by our check style to name variable with only one letter, replace `e` with `ex`.

2018-03-28 08:06 UTC, sashadidukh commented on server/appenders/hbase-appender/src/main/java/org/kaaproject/kaa/server/appenders/hbase/appender/HBaseLogEventDao.java
> +    LOG.info("Starting creation of table:  {}",keyspace + ":" + table);
Add the space before `keyspace`.

2018-03-28 08:06 UTC, sashadidukh commented on server/appenders/hbase-appender/src/main/java/org/kaaproject/kaa/server/appenders/hbase/appender/HBaseLogEventDao.java
> +      LOG.error("Ops",e);
See related comment above.

2018-03-28 08:17 UTC, sashadidukh commented
Hi, @JoaoRei!
Could you add the documentation to the HBase log appender?

See existed [log appenders](https://kaaproject.github.io/kaa/docs/latest/Programming-guide/Key-platform-features/Data-collection/#log-appenders) doc and its [implementation](https://github.com/kaaproject/kaa/blob/master/doc/Programming-guide/Key-platform-features/Data-collection/index.md).
Also, take a look at the [Documentation style](https://kaaproject.github.io/kaa/docs/latest/How-to-contribute/Style-guide/) guide. It's better to open the new Pull Request with the documentation.

2018-04-04 20:37 UTC, rasendubi commented
@JoaoRei I don't want this PR to rot. I see the comments are non-critical, so I'll merge it now.

Let's address the comments in a separate PR if you have time and will ;)

2018-04-04 20:37 UTC, merged

2018-04-05 10:32 UTC, JoaoRei commented
@Alexey Shmalko

Hello!
Thank you very much for your support and feedback!

I am willing to continue working on this contribution by correcting the
pending issues and providing a documentation for the log appender
implementation (:

I am sorry for the late response, but i didn't have the required time to
correct them since I am writing my master thesis. It is almost finished and
in the next week I will have plenty of time to get back to work on this
project! I will try to address the issues in a new separate PR soon!

Once again, thank you very much for your understanding and support along
the process (:

Best regards,
João Rei

2018-04-04 21:37 GMT+01:00 Alexey Shmalko <notifications@github.com>:

> Merged #1535 <https://github.com/kaaproject/kaa/pull/1535>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kaaproject/kaa/pull/1535#event-1557395854>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/Aj5csqU_Bf_mBrmRjZJDrlYzHuLSuUgXks5tlS8lgaJpZM4S5h0A>
> .
>